# Book settings
title: Urban Grammar AI | WP1 - Data Processing
author: Dani Arribas-Bel, Martin Fleischmann
logo: logo.svg

execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/urbangrammarai/data_processing
launch_buttons:
  binderhub_url: https://mybinder.org
html:
  use_repository_button: true
